palantir/tslint-react

- README.md
- src/rules/jsxAlignmentRule.ts
- test/rules/jsx-alignment/test.tsx.lint
- test/rules/jsx-alignment/tslint.json
> jsx-alignment rule implementation

- scripts/newRule.js
- If the `${ruleCamelName}Rule.ts` file exists, stop the new rule creation (so nothing is overwritten).
- Switch from `mkDir` to `mkDirSync` so the folder definitely exists by the time the test files are created.
- Add new line to end of rule file.
> newRule improvements

- package.json
- tslint-react.json
- tslint.json
- Enabled `jsx-curly-spacing` rule
- TSLint 4.0 and TypeScript 2.0 required
> Prepare release v2.0.0

- circle.yml
- tsconfig.json
Yarn is now installed by default on Ubuntu 14 containers in Circle.
> Simplify circle.yml

- README.md
- src/rules/jsxBooleanValueRule.ts
- test/rules/jsx-boolean-value/always/test.tsx.lint
- test/rules/jsx-boolean-value/always/tslint.json
- test/rules/jsx-boolean-value/false/test.tsx.lint
- test/rules/jsx-boolean-value/false/tslint.json
- test/rules/jsx-boolean-value/never/test.tsx.lint
- test/rules/jsx-boolean-value/never/tslint.json
- test/rules/jsx-boolean-value/true/test.tsx.lint
- test/rules/jsx-boolean-value/true/tslint.json
Created a `tslint-react` equivalent rule for `eslint-plugin-react`'s [`jsx-boolean-value`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-boolean-value.md) rule.
> Add new rule jsx-boolean-value rule

- README.md
Breaking change in 2.5.0 is a little confusing when the README states the opposite.
> jsx-wrap-multiline now defaults to on

- src/rules/jsxNoLambdaRule.ts
- test/rules/jsx-no-lambda/test.tsx.lint
This PR contain rewrite for `jsx-no-lambda` that will report error only if arrow function or function expression are provided directly as attribute expression. 
This PR replaces AST Walker with function.
Please suggest other edge cases that should be also reported.
[bugfix] `jsx-no-lambda` checks if lambda is passed directly to attribute
> jsx-no-lambda checks if lambda is passed directly to attribute (fixes #29)

- src/rules/jsxNoBindRule.ts
- test/rules/jsx-no-bind/test.tsx.lint
- test/rules/jsx-no-bind/tslint.json
- tslint-react.json
> Add new rule: jsx-no-bind

- README.md
- package.json
contributors: @lvillani @IllusionMH
> Prepare v2.6.0

- src/rules/jsxAlignmentRule.ts
In TS 2.3, the `attributes` is a separate node type instead of an array.
To support it without requiring a version bump, make the attributes argument an union type, and grab the `properties` property if the argument is not an array.
c.f. https://github.com/Microsoft/TypeScript/blob/2e43c869b/lib/typescript.d.ts#L1019-L1020
Fixes #87
> Update jsx-alignment for TS 2.3

- src/rules/jsxNoLambdaRule.ts
- test/rules/jsx-no-lambda/test.tsx.lint
Fixes issue https://github.com/palantir/tslint-react/issues/26
The main performance drop with arrow function as prop is due to pure components re-rendering when it could be avoided. The creation of a new function is not a real problem.
The `ref` attribute is not part of the props so it's ok to use an arrow function here.
See: https://github.com/facebook/react/issues/9086#issuecomment-283348191
Rather than adding a configuration, I simply ignore "ref" attribute. I think that this is what makes the more sense in most situations.
> jsx-no-lambda: allow lambdas on ref attribute

- README.md
- package.json
> Explicit peer dependencies

- README.md
- currently it implies that it should be set to a string, but it needs to be in an array to be valid
> fix jsx-boolean-value doc

- src/rules/jsxKeyRule.ts
- test/rules/jsx-key/test.tsx.lint
This looks for `key` in an object literal being spread into the component.
Closes #122
> Check key in JSX spread attribute (jsx-key)

- package.json
- src/rules/jsxAlignmentRule.ts
- src/rules/jsxWrapMultilineRule.ts
- test/rules/jsx-wrap-multiline/test.tsx.lint
- yarn.lock
Fixes #124
Added a check for ts.syntaxKind.JsxFragment in jsx-wrap-multiline.  A newer version of `tsutils` has this check as well, but I was unsure of the policy for updating dependencies.  If you would rather upgrade I will do that instead.
Add tests to verify positive and negative cases. Upgrade ts devDependency to 2.6.2.
> Support JSX Fragment syntax for jsx-wrap-multiline.

- README.md
- package.json
- New rule: `jsx-ban-elements` #137
> Prepare release 3.4.0

- src/rules/jsxUseTranslationFunctionRule.ts
- test/rules/jsx-use-translation-function/allow-both/test.tsx.lint
- test/rules/jsx-use-translation-function/allow-both/tslint.json
- test/rules/jsx-use-translation-function/allow-htmlentities/test.tsx.lint
This case came up running lint across our larger code base, where strings like `{var1}:&nbsp;{var2}` were incorrectly flagged when both punctuation and HTML entities were allowed.
> Fixes for translation lint where punctuation and HTML entities are side by side

- src/rules/jsxBanElementsRule.ts
- src/rules/jsxCurlySpacingRule.ts
> Allow js files to be linted by jsx-ban-elements and jsx-curly-spacing rules

- README.md
- src/rules/jsxSpaceBeforeTrailingSlashRule.ts
- test/rules/jsx-space-before-trailing-slash/test.tsx.lint
- test/rules/jsx-space-before-trailing-slash/tslint.json
duplicate of https://github.com/palantir/tslint-react/pull/144 for build reasons, all credit to @no23reason!
> [new-rule] add jsx-space-before-trailing-slash rule

- src/rules/jsxCurlySpacingRule.ts
- test/rules/jsx-curly-spacing/never/test.tsx.fix
- test/rules/jsx-curly-spacing/never/test.tsx.lint
The problem was caused by `getTokensCombinedText` returning an incorrect
slice which caused the multiline check to fail.
> Fix issue #140

- src/rules/jsxKeyRule.ts
- test/rules/jsx-key/test.tsx.lint
Fix #187
The current implementation miss the case where an arrow function returns `()`; i.e.
```js
[3, 4, 5].map(x => (<App />));
[3, 4, 5].map(x => (<App>app</App>));
```
It should be the following code instead.
```js
[3, 4, 5].map(x => (<App key={x} />));
[3, 4, 5].map(x => (<App key={x}>app</App>));
```
> Fix jsx-key can't detect error in parenthesized expression

- src/rules/jsxWrapMultilineRule.ts
- test/rules/jsx-wrap-multiline/test.tsx.lint
There was a bug in this rule: having the opening parenthesis on a new line before the opening tag, but the closing parenthesis on the same line as the closing tag, would not trigger this rule.
This was caused by the fact that the `index` variable (as calculated by `siblings.indexOf`) was equal to -1 in some cases.
The `index` is now calculated by checking just the `pos` and `end` fields of a `node`, instead of the default object equality that `indexOf` uses.
With this change, the check that tested whether the node started with a newline is no longer needed (and with it, also the `prevTokenKind` variable is no longer needed).
Also, two tests have been added:
- A multiline JSX component with the closing parenthesis on a new line, but the opening parenthisis on the same line
- A multiline …
> Fix jsx-wrap-multiline rule for closing parenthesis

- README.md
- src/rules/jsxSpaceBeforeTrailingSlashRule.ts
- test/rules/jsx-space-before-trailing-slash/test.tsx.fix
Hi,
This PR adds an auto fixer for the jsxSpaceBeforeTrailingSlash rule, along with a test and readme update.
The auto-fix uses `appendText` to add a single space before offending closing tags.
Let me know if it's missing anything! Shoutout to @zapo for co-driving to do this! 🙌
> Add auto fixer for jsx-space-before-trailing-slash

- README.md
- src/rules/jsxSelfCloseRule.ts
- test/rules/jsx-self-close/test.lint.fix
- test/rules/jsx-self-close/test.tsx.lint
Hi,
This PR adds an auto fixer for the jsxSelfClose rule, along with a test and readme update.
As we throw an error when there are no node children, the fix just keeps the opening element and makes him self-closing
I'll keep an eye on the PR if changes are needed ! 😄
> Add auto fixer for jsx-self-close-rule

- README.md
- src/rules/noAccessStateInSetstateRule.ts
- test/rules/no-access-state-in-setstate/test.tsx.lint
- test/rules/no-access-state-in-setstate/tslint.json
Fixes #172 (and #80 to some extent)
Took ESLint-plugin-React's no-access-state-in-setstate rule and implemented it in tslint-react. I know no maintainer seems to have reviewed #172 yet, but I took a swing at it anyway, hope that was okay! 
You will find that I did the checks with pretty simple string comparisons (e.g. `expression.getText().indexOf("this.state.") !== -1;`). I started creating the checks with actually using the AST but found that the string solution is not only imho more reliable but of course also a lot easier to write and understand. But maybe there're better ways to check it!
No matter the way the check of the ``this.setState`` argument is implemented, there are still ways to bypass the check and creating - if you want so - false-positives.
```ts
class MyReactComponent …
```
> Add new rule noAccessStateInSetstate

- package.json
- src/rules/jsxAlignmentRule.ts
- src/rules/jsxBanElementsRule.ts
- src/rules/jsxBanPropsRule.ts
- src/rules/jsxBooleanValueRule.ts
- src/rules/jsxCurlySpacingRule.ts
- src/rules/jsxEqualsSpacingRule.ts
- src/rules/jsxKeyRule.ts
- src/rules/jsxNoBindRule.ts
- src/rules/jsxNoLambdaRule.ts
- src/rules/jsxNoMultilineJsRule.ts
- src/rules/jsxNoStringRefRule.ts
- src/rules/jsxSelfCloseRule.ts
- src/rules/jsxSpaceBeforeTrailingSlashRule.ts
- src/rules/jsxUseTranslationFunctionRule.ts
- src/rules/jsxWrapMultilineRule.ts
- tsconfig.json
- tslint.json
- yarn.lock
BREAKING: drop support for TS < 2.8 (we're now using [tsutils 3.0](https://github.com/ajafff/tsutils/releases/tag/v3.0.0))
> Upgrade dependencies

- src/rules/jsxWrapMultilineRule.ts
- test/rules/jsx-wrap-multiline/test.tsx.lint
check the child node if it satisfies the criteria.
> 205 (jsx-wrap-multiline): fix check for nested JSX

- src/rules/jsxWhitespaceLiteralRule.ts
- test/rules/jsx-whitespace-literal/test.tsx.fix
- test/rules/jsx-whitespace-literal/test.tsx.lint
- test/rules/jsx-whitespace-literal/tslint.json
Added `jsx-whitespace-literal` rule with some tests
```javascipt
{
"rules": {
"jsx-whitespace-literal": true
}
}
```
Not sure if i covered all test
> add new rule: jsx-whitespace-literal
